### PR TITLE
Fixing a Bug

### LINKED ISSUE #2: #INC-5312: Missing image
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by jessitron**
# Description

Closes #2 

This site has way worse problems than this

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks jessitron, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by jessitron** [comment]
Screen Shot 2022-11-10 at 4 51 34 PM

i hypothesize that the failing check means "there is not an image attached to the PR"

**Comment by jessitron** [comment]
It probably requires the image in the PR description, but let's find out. It does not give a useful error message
and neither does Ness.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job jessitron! You're now able to merge the PR.

**Pull request merged**
